CREATE TABLE raw_data (
    course_code TEXT,
    course_name TEXT,
    term TEXT,
    allow_repeats TEXT,
    us_credits TEXT,
    instructor TEXT,
    level TEXT,
    corresponding_programs TEXT,
    abbreviation TEXT,
    course_type TEXT,
    department TEXT,
    corresponding_collections_codes TEXT,
    corresponding_collections TEXT,
    corresponding_program_codes TEXT,
    marking_scheme TEXT,
    offered_for_non_degree_students TEXT,
    scheme TEXT,
    ects TEXT,
    learning_outcomes TEXT,
    learning_activities_and_teaching_methods TEXT,
    assessment TEXT,
    course_contents TEXT,
    background_and_overall_aim TEXT,
    contact_details TEXT,
    course_prerequisites TEXT,
    instructor_email TEXT
);