\set ON_ERROR_STOP on
\pset pager off

\if :{?schema}
\else
  \set schema sandbox
\endif

SET search_path TO :"schema";

BEGIN;


-- Core tables

CREATE TABLE "Department" (
  DEPARTMENT_ID      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DEPARTMENT_NAME    VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE "Program" (
  PROGRAM_ID                INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PROGRAM_NAME              VARCHAR(200) NOT NULL UNIQUE,
  DEPARTMENT_ID             INT NOT NULL REFERENCES "Department"(DEPARTMENT_ID),
  PROGRAM_COORDINATOR_EMAIL VARCHAR(254),
  PROGRAM_LEARNING_OUTCOME  TEXT,
  PROGRAM_DESCRIPTION       TEXT
);

CREATE TABLE "Instructor" (
  INSTRUCTOR_ID     INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INSTRUCTOR_FIRST_NAME  VARCHAR(100) NOT NULL,
  INSTRUCTOR_LAST_NAME   VARCHAR(100) NOT NULL,
  INSTRUCTOR_EMAIL  VARCHAR(254) UNIQUE,
  INSTRUCTOR_OFFICE VARCHAR(100)
);

CREATE TABLE "Student" (
  STUDENT_ID         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STUDENT_FIRST_NAME VARCHAR(100) NOT NULL,
  STUDENT_LAST_NAME  VARCHAR(100) NOT NULL,
  STUDENT_EMAIL      VARCHAR(254) UNIQUE,
  STUDENT_START_YEAR INT NOT NULL CHECK (STUDENT_START_YEAR >= 2020),
  PROGRAM_ID         INT NOT NULL REFERENCES "Program"(PROGRAM_ID)
);

CREATE TABLE "Term" (
CREATE TABLE "Term" (
  TERM_ID    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TERM_NAME  VARCHAR(100) NOT NULL UNIQUE,
  START_DATE DATE NOT NULL,
  END_DATE   DATE NOT NULL,
  CHECK (END_DATE > START_DATE)
);

CREATE TABLE "Course" (
  COURSE_ID      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COURSE_CODE    VARCHAR(20) NOT NULL,
  COURSE_NAME    VARCHAR(200) NOT NULL,
  COURSE_CREDITS INT NOT NULL CHECK (COURSE_CREDITS > 0),
  DEPARTMENT_ID  INT NOT NULL REFERENCES "Department"(DEPARTMENT_ID),
  TERM_ID        INT NOT NULL REFERENCES "Term"(TERM_ID) ON DELETE RESTRICT,

  COURSE_DESCRIPTION       TEXT,
  PREREQ_TEXT              TEXT,
  COURSE_LEARNING_OUTCOMES TEXT,

  EXCLUDES_COURSE_ID          INT REFERENCES "Course"(COURSE_ID),
  HARD_PREREQUISITE_COURSE_ID INT REFERENCES "Course"(COURSE_ID),

  CHECK (EXCLUDES_COURSE_ID IS NULL OR EXCLUDES_COURSE_ID <> COURSE_ID),
  CHECK (HARD_PREREQUISITE_COURSE_ID IS NULL OR HARD_PREREQUISITE_COURSE_ID <> COURSE_ID),

  -- Allow same course code/name in different terms, but prevent duplicates within a term
  UNIQUE (COURSE_CODE, TERM_ID),
  UNIQUE (COURSE_NAME, TERM_ID)
);

CREATE INDEX IDX_COURSE_DEPARTMENT ON "Course"(DEPARTMENT_ID);
CREATE INDEX IDX_COURSE_TERM ON "Course"(TERM_ID);
CREATE INDEX IDX_STUDENT_PROGRAM ON "Student"(PROGRAM_ID);


-- Join tables

CREATE TABLE "STUDENT_REQUESTED_ENROLLMENT_IN_COURSE" (
  STUDENT_ID INT NOT NULL REFERENCES "Student"(STUDENT_ID) ON DELETE CASCADE,
  COURSE_ID  INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE RESTRICT,
  PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

CREATE TABLE "STUDENT_ENROLLED_IN_COURSE" (
  STUDENT_ID INT NOT NULL REFERENCES "Student"(STUDENT_ID) ON DELETE CASCADE,
  COURSE_ID  INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE RESTRICT,
  PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

CREATE TABLE "STUDENT_PASSED_COURSE" (
  STUDENT_ID INT NOT NULL REFERENCES "Student"(STUDENT_ID) ON DELETE CASCADE,
  COURSE_ID  INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE RESTRICT,
  GRADE      VARCHAR(5) NOT NULL,
  PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

CREATE TABLE "TEACHING_COURSE" (
  INSTRUCTOR_ID INT NOT NULL REFERENCES "Instructor"(INSTRUCTOR_ID) ON DELETE CASCADE,
  COURSE_ID     INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE RESTRICT,
  PRIMARY KEY (INSTRUCTOR_ID, COURSE_ID)
);


CREATE TABLE "DEPARTMENT_INSTRUCTOR" (
  DEPARTMENT_ID INT NOT NULL REFERENCES "Department"(DEPARTMENT_ID) ON DELETE CASCADE,
  INSTRUCTOR_ID INT NOT NULL REFERENCES "Instructor"(INSTRUCTOR_ID) ON DELETE CASCADE,
  PRIMARY KEY (DEPARTMENT_ID, INSTRUCTOR_ID)
);

CREATE TABLE "PROGRAM_REQUIRED_COURSE" (
  PROGRAM_ID            INT NOT NULL REFERENCES "Program"(PROGRAM_ID) ON DELETE CASCADE,
  COURSE_ID             INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE CASCADE,
  AVAILABLE_FROM_YEAR_N INT NOT NULL CHECK (AVAILABLE_FROM_YEAR_N >= 1),
  PRIMARY KEY (PROGRAM_ID, COURSE_ID)
);

CREATE TABLE "PROGRAM_ELECTIVE_COURSE" (
  PROGRAM_ID            INT NOT NULL REFERENCES "Program"(PROGRAM_ID) ON DELETE CASCADE,
  COURSE_ID             INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE CASCADE,
  AVAILABLE_FROM_YEAR_N INT NOT NULL CHECK (AVAILABLE_FROM_YEAR_N >= 1),
  PRIMARY KEY (PROGRAM_ID, COURSE_ID)
);

CREATE TABLE "PROGRAM_MANDATORY_ELECTIVE_COURSE" (
  PROGRAM_ID            INT NOT NULL REFERENCES "Program"(PROGRAM_ID) ON DELETE CASCADE,
  COURSE_ID             INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE CASCADE,
  AVAILABLE_FROM_YEAR_N INT NOT NULL CHECK (AVAILABLE_FROM_YEAR_N >= 1),
  PRIMARY KEY (PROGRAM_ID, COURSE_ID)
);

-- Class and Lesson

CREATE TABLE "Class" (
  CLASS_ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLASS_NAME VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE "Lesson" (
  LESSON_ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COURSE_ID   INT NOT NULL REFERENCES "Course"(COURSE_ID) ON DELETE CASCADE,
  TERM_ID     INT NOT NULL REFERENCES "Term"(TERM_ID) ON DELETE CASCADE,
  CLASS_ID    INT NOT NULL REFERENCES "Class"(CLASS_ID) ON DELETE CASCADE,
  LESSON_TYPE VARCHAR(50),
  LESSON_TIME TIMESTAMP NOT NULL,
  FOREIGN KEY (COURSE_ID, TERM_ID)
    REFERENCES "COURSE_TERM"(COURSE_ID, TERM_ID) ON DELETE RESTRICT
);

CREATE INDEX idx_course_department ON "Course"(DEPARTMENT_ID);
CREATE INDEX idx_student_program ON "Student"(PROGRAM_ID);
CREATE INDEX idx_lesson_course_term ON "Lesson"(COURSE_ID, TERM_ID);

COMMIT;
